import Head from 'next/head';
import Image from 'next/image';
import { Card } from 'antd';

export default function Home() {
	return (
		<div className='container flex flex-col justify-center items-center'>
			<Head>
				<title>
					Sparter | NextJS Starter for Single Page Applications
				</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='w-full h-full'>
				<h1 className='text-6xl text-center mb-8'>
					Welcome to Sparter!
				</h1>

				<p className='text-2xl text-center leading-relaxed mb-8'>
					This Single Page Application starter is built on Next.js. It
					comes with Ant Design, TailwindCSS, ESLint and Prettier
					pre-installed and a basic configuration that you can modify
					to suit your project.
				</p>

				<p className='text-2xl text-center leading-relaxed mb-8'>
					Get started by editing{' '}
					<code className='bg-gray-100 rounded-md p-3'>
						pages/index.js
					</code>
				</p>

				<div className='grid grid-cols-2 grid-rows-2 gap-4'>
					<a
						className='p-6 text-left border rounded-md transition duration-150 ease-linear hover:border-blue-500 active:border-blue-500 focus:border-blue-500'
						href='https://nextjs.org/docs'
					>
						<Card className='border-none'>
							<h2 className='text-2xl mb-4'>
								Documentation &rarr;
							</h2>
							<p className='text-xl'>
								Find in-depth information about Next.js features
								and API.
							</p>
						</Card>
					</a>

					<a
						className='p-6 text-left border rounded-md transition duration-150 ease-linear hover:border-blue-500 active:border-blue-500 focus:border-blue-500'
						href='https://nextjs.org/learn'
					>
						<Card className='border-none'>
							<h2 className='text-2xl mb-4'>Learn &rarr;</h2>
							<p className='text-xl'>
								Learn about Next.js in an interactive course
								with quizzes!
							</p>
						</Card>
					</a>

					<a
						className='p-6 text-left border rounded-md transition duration-150 ease-linear hover:border-blue-500 active:border-blue-500 focus:border-blue-500'
						href='https://github.com/vercel/next.js/tree/master/examples'
					>
						<Card className='border-none'>
							<h2 className='text-2xl mb-4'>Examples &rarr;</h2>
							<p className='text-xl'>
								Discover and deploy boilerplate example Next.js
								projects.
							</p>
						</Card>
					</a>

					<a
						className='p-6 text-left border rounded-md transition duration-150 ease-linear hover:border-blue-500 active:border-blue-500 focus:border-blue-500'
						href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					>
						<Card className='border-none'>
							<h2 className='text-2xl mb-4'>Deploy &rarr;</h2>
							<p className='text-xl'>
								Instantly deploy your Next.js site to a public
								URL with Vercel.
							</p>
						</Card>
					</a>
				</div>
			</main>

			<footer className='w-full h-24 flex justify-center items-center'>
				<a
					className='flex justify-center items-center flex-grow-1'
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className='h-4 ml-2'>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}
